// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc7_CookieAuthentication.Data;

#nullable disable

namespace Mvc10_CookieAuthentication.Migrations
{
    [DbContext(typeof(AccountContext))]
    partial class AccountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mvc10_CookieAuthentication.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "R001",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = "R002",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = "R003",
                            Name = "RD"
                        },
                        new
                        {
                            Id = "R004",
                            Name = "Operation"
                        });
                });

            modelBuilder.Entity("Mvc10_CookieAuthentication.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "U001",
                            Email = "kevinxi@gmail.com",
                            Name = "Kevin@gmail.com",
                            Nickname = "無敵霸主",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            PhoneNo = "0925-155222"
                        },
                        new
                        {
                            Id = "U002",
                            Email = "marylee@gmail.com",
                            Name = "Mary@gmail.com",
                            Nickname = "飛天女俠",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            PhoneNo = "0935-123123"
                        },
                        new
                        {
                            Id = "U003",
                            Email = "johnwei@gmail.com",
                            Name = "John@gmail.com",
                            Nickname = "小李飛刀",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            PhoneNo = "0955-456456"
                        });
                });

            modelBuilder.Entity("Mvc10_CookieAuthentication.Models.UserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "U001",
                            RoleId = "R001"
                        },
                        new
                        {
                            UserId = "U002",
                            RoleId = "R002"
                        },
                        new
                        {
                            UserId = "U003",
                            RoleId = "R003"
                        },
                        new
                        {
                            UserId = "U003",
                            RoleId = "R004"
                        });
                });

            modelBuilder.Entity("Mvc10_CookieAuthentication.Models.UserRoles", b =>
                {
                    b.HasOne("Mvc10_CookieAuthentication.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mvc10_CookieAuthentication.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mvc10_CookieAuthentication.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Mvc10_CookieAuthentication.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
