// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc10_Razor.Data;

#nullable disable

namespace Mvc10_Razor.Migrations
{
    [DbContext(typeof(CardContext))]
    partial class CardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mvc10_Razor.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brief")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brief = "特斯拉創辦人 伊隆·馬斯克",
                            Name = "Elon Musk",
                            Photo = "ElonMusk.jpg",
                            WikiUrl = "https://goo.gl/46xeXx"
                        },
                        new
                        {
                            Id = 2,
                            Brief = "Facebook馬克·祖伯克",
                            Name = "Mark Zuckerberg",
                            Photo = "MarkZuckerberg.jpg",
                            WikiUrl = "https://goo.gl/BktGGA"
                        },
                        new
                        {
                            Id = 3,
                            Brief = "蘋果創辦人 史提夫·賈伯斯",
                            Name = "Steve Jobs",
                            Photo = "SteveJobs.jpg",
                            WikiUrl = "https://goo.gl/nAiX0y"
                        },
                        new
                        {
                            Id = 4,
                            Brief = "帝國元帥  維達",
                            Name = "Vader",
                            Photo = "Vader.jpg",
                            WikiUrl = "http://bit.ly/3F5xw2w"
                        },
                        new
                        {
                            Id = 5,
                            Brief = "星際大戰 達斯摩",
                            Name = "Darth Mual",
                            Photo = "DarthMual.jpg",
                            WikiUrl = "https://goo.gl/5obLhX"
                        },
                        new
                        {
                            Id = 6,
                            Brief = "星際大戰 女絕地武士Twilek",
                            Name = "White Twilek",
                            Photo = "WhiteTwilek.jpg",
                            WikiUrl = "https://goo.gl/reKzAu"
                        },
                        new
                        {
                            Id = 7,
                            Brief = "星際大戰 歐比旺Obiwan",
                            Name = "Obiwan",
                            Photo = "Obiwan.jpg",
                            WikiUrl = "http://bit.ly/33gxdgt"
                        },
                        new
                        {
                            Id = 8,
                            Brief = "德國總理 梅克爾",
                            Name = "Merkel",
                            Photo = "Merkel.jpg",
                            WikiUrl = "http://bit.ly/33huSlv"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
