// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc7_Routing.Data;

#nullable disable

namespace Mvc7_Routing.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20230409094533_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mvc7_Routing.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("汽車廠牌製造商");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("汽車分類");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("汽車名稱");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("汽車售價");

                    b.Property<int>("SoldNumber")
                        .HasColumnType("int")
                        .HasComment("汽車年度銷售數字");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasComment("汽車年份");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Brand = "Mercedes",
                            Category = "轎車",
                            ImageUrl = "Mercedes_AMG_S63.jpg",
                            Name = "AMG S63",
                            Price = 145695m,
                            SoldNumber = 120,
                            Year = 2023
                        },
                        new
                        {
                            Id = 1002,
                            Brand = "Audi",
                            Category = "轎車",
                            ImageUrl = "Audi_S8.jpg",
                            Name = "S8",
                            Price = 116875m,
                            SoldNumber = 200,
                            Year = 2021
                        },
                        new
                        {
                            Id = 1003,
                            Brand = "BMW",
                            Category = "轎車",
                            ImageUrl = "BMW_M3.jpg",
                            Name = "M3",
                            Price = 66495m,
                            SoldNumber = 85,
                            Year = 2021
                        },
                        new
                        {
                            Id = 1004,
                            Brand = "AlfaRomeo",
                            Category = "轎車",
                            ImageUrl = "AlfaRomeo_GiuliaQuadrifoglio.jpg",
                            Name = "Giulia Quadrifoglio",
                            Price = 73595m,
                            SoldNumber = 62,
                            Year = 2022
                        },
                        new
                        {
                            Id = 1005,
                            Brand = "Mercedes",
                            Category = "SUV",
                            ImageUrl = "MercedesBenz_GLS.jpg",
                            Name = "GLS Class",
                            Price = 68045m,
                            SoldNumber = 250,
                            Year = 2019
                        },
                        new
                        {
                            Id = 1006,
                            Brand = "Porsche",
                            Category = "SUV",
                            ImageUrl = "Porsche_Cayenne.jpg",
                            Name = "Cayenne",
                            Price = 60650m,
                            SoldNumber = 160,
                            Year = 2023
                        },
                        new
                        {
                            Id = 1007,
                            Brand = "Honda",
                            Category = "SUV",
                            ImageUrl = "Honda_CRV.jpg",
                            Name = "CR-V",
                            Price = 24985m,
                            SoldNumber = 1200,
                            Year = 2023
                        },
                        new
                        {
                            Id = 1008,
                            Brand = "Bugatti",
                            Category = "跑車",
                            ImageUrl = "Bugatti_Chiron.jpg",
                            Name = "Chiron",
                            Price = 2998000m,
                            SoldNumber = 10,
                            Year = 2023
                        },
                        new
                        {
                            Id = 1009,
                            Brand = "Lamborghini",
                            Category = "跑車",
                            ImageUrl = "Lamborghini_Huracan.jpg",
                            Name = "Huracan",
                            Price = 203295m,
                            SoldNumber = 30,
                            Year = 2022
                        },
                        new
                        {
                            Id = 1010,
                            Brand = "Porsche",
                            Category = "跑車",
                            ImageUrl = "Porsche_718Boxster.jpg",
                            Name = "718 Boxster",
                            Price = 57050m,
                            SoldNumber = 49,
                            Year = 2019
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
