// <auto-generated />
using EFCore_DbContextConfig.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreDbContextConfig.Migrations
{
    [DbContext(typeof(CardContext))]
    [Migration("20221211083013_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore_DbContextConfig.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brief = "特斯拉創辦人 伊隆·馬斯克",
                            Name = "Elon Musk",
                            Photo = "ElonMusk.jpg",
                            WikiUrl = "https://goo.gl/46xeXx"
                        },
                        new
                        {
                            Id = 2,
                            Brief = "Facebook創辦人 馬克·祖伯克",
                            Name = "Mark Zuckerberg",
                            Photo = "MarkZuckerberg.jpg",
                            WikiUrl = "https://goo.gl/BktGGA"
                        },
                        new
                        {
                            Id = 3,
                            Brief = "蘋果創辦人 史提夫·賈伯斯",
                            Name = "Steve Jobs",
                            Photo = "SteveJobs.jpg",
                            WikiUrl = "https://goo.gl/nAiX0y"
                        },
                        new
                        {
                            Id = 4,
                            Brief = "帝國元帥  維達",
                            Name = "Vader",
                            Photo = "Vader.jpg",
                            WikiUrl = "https://en.wikipedia.org/wiki/Darth_Vader"
                        },
                        new
                        {
                            Id = 5,
                            Brief = "星際大戰 達斯摩",
                            Name = "Darth Mual",
                            Photo = "DarthMual.jpg",
                            WikiUrl = "https://goo.gl/5obLhX"
                        },
                        new
                        {
                            Id = 6,
                            Brief = "星際大戰 女絕地武士Twilek",
                            Name = "White Twilek",
                            Photo = "WhiteTwilek.jpg",
                            WikiUrl = "https://goo.gl/reKzAu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
