// <auto-generated />
using EFCore_CodeFirstNewDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_CodeFirstNewDB.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20220904054455_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore_CodeFirstNewDB.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<string>("BlogName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            BlogName = "Kevin's Blog",
                            Url = "blogs.com.tw/kevin",
                            UserId = 1
                        },
                        new
                        {
                            BlogId = 2,
                            BlogName = "David's Blog",
                            Url = "blogs.com.tw/david",
                            UserId = 2
                        },
                        new
                        {
                            BlogId = 3,
                            BlogName = "Mary's Blog",
                            Url = "blogs.com.tw/mary",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("EFCore_CodeFirstNewDB.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            BlogId = 1,
                            Content = "ASP.NET Core Tutorial",
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            PostId = 2,
                            BlogId = 1,
                            Content = "Entity Framework Core Tutorial",
                            Title = "Entity Framework Core"
                        },
                        new
                        {
                            PostId = 3,
                            BlogId = 2,
                            Content = "Vue.js Tutorial",
                            Title = "Vue.js"
                        },
                        new
                        {
                            PostId = 4,
                            BlogId = 3,
                            Content = "Bootstrap 4 Tutorial",
                            Title = "Bootstrap 4"
                        });
                });

            modelBuilder.Entity("EFCore_CodeFirstNewDB.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kevin@gmail.com",
                            UserName = "Kevin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "david@gmail.com",
                            UserName = "David"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mary@gmail.com",
                            UserName = "Mary"
                        });
                });

            modelBuilder.Entity("EFCore_CodeFirstNewDB.Models.Blog", b =>
                {
                    b.HasOne("EFCore_CodeFirstNewDB.Models.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EFCore_CodeFirstNewDB.Models.Post", b =>
                {
                    b.HasOne("EFCore_CodeFirstNewDB.Models.Blog", "Blog")
                        .WithMany("Post")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("EFCore_CodeFirstNewDB.Models.Blog", b =>
                {
                    b.Navigation("Post");
                });

            modelBuilder.Entity("EFCore_CodeFirstNewDB.Models.User", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
